### PR TITLE
[DDW-588] Refuse inserts over decimal separator

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes an issue with `NumericInput` when entering numbers after having selected the decimal separator in a numeric input configured to always show a specific precision. This resulted in weird numbers being produced because the decimal separator was deleted This is now simply refused, so the number is not changed at all:

https://user-images.githubusercontent.com/172414/113428477-269ce400-93d7-11eb-9d0a-8f86888cb67b.mp4

How to test:

- [ ] Go to the storybook "numeric input > decimals places (6)" and try to insert (type) new numbers while having a selection that includes the decimal separator. This should be refused in all cases (it should never be possible to "delete" the decimal separator with the setting of having a fixed required number of decimal places)

### Test Scenarios

**Scenario 1 -  Select separator and insert a number**
```gherkin
Given that I am on the "NumericInput" Screen
And a value is inserted in the field
When I select the decimal separator on the number
And I insert a number to replace the selection
Then the decimal separator is not replaced with the value
And the cursor moves to the right of the selection
```

**Scenario 2 -  Select separator and at least a digit and insert a number**
```gherkin
Given that I am on the "NumericInput" Screen
And a value is inserted in the field
When I select the decimal separator and at least one digit before or after it
And I insert a number to replace the selection
Then the decimal separator is not replaced with the value
And the cursor moves to the right of the selection
```

### CODE REVIEW

**Review by ManusMcCole — APPROVED** [review]
LGTM 👍

**Comment by gabriela-ponce** [comment]
@DominikGuzei This looks good. I was wondering if this should be consistent and be implemented to the thousand separators as well, but I think the user could be limited if they want to replace part of the whole number. What do you think?

Also when you delete the value in _NumericInput_ then you can't insert any value again and have to refresh the page to be able to do so. I'm just wondering if this is affected by this change in case the behavior transfers to Daedalus. Check [this video](https://drive.google.com/file/d/1KVSVa2KmoZWI48s4V8UfZzbY3jCi9ixj/view?usp=sharing).

**Comment by DominikGuzei** [comment]
thanks for the feedback @gabriela-ponce, I think it's ok if the users overwrite the thousand separators 👍 
The second issue you found is definitely a bug

**Comment by DominikGuzei** [comment]
@gabriela-ponce please test again, the issue `Also when you delete the value in NumericInput then you can't insert any value again and have to refresh the page to be able to do so.` should be fixed now

**Review by gabriela-ponce — APPROVED** [review]
Looks great, nice work 🎉

**Review by ManusMcCole — APPROVED** [review]

**Pull request merged**
