### PR TITLE
Refactors Checkbox: Component, Skin, and Theme. Adds theme API's for all components.

### PR DESCRIPTION
**Pull request by MarcusHurney**
- Adds composeTheme util function.

- Updates Storybook to use refactored Checkbox (component, theme, and skin). 

- Adds a composed theme example of Checkbox in its stories (makes use of themeOverrides prop).  

- Removes Checkbox from raw folder.

- Installs babel-plugin-transform-object-rest-spread and uses it in the npm script "js" and in storybook/webpack.config.js

### CODE REVIEW

**Comment by MarcusHurney** [comment]
@DominikGuzei  What's the best way to do that now that I've already made the PR? I pushed before writing the description of changes, but left them in them in a comment on this PR (not ideal obviously). Should I force push a commit with an amended message?

**Comment by DominikGuzei** [comment]
@MarcusHurney no just push another commit - we are not doing any kind of commit squashing etc. to keep things simple 😉

**Comment by MarcusHurney** [comment]
@DominikGuzei I pushed another commit with a description of the refactor for Checkbox. I have more changes ready to commit for the FormField, Input, and TextArea refactors. One tricky thing about this is the fact that many other components inherit from FormField, in order to run storybook without errors, I've commented out the stories for the components I've yet to refactor that inherit from FormField: AutoComplete, NumericInput, and Select. Trying to combine all these refactors into one gigantic PR and merging into master doesn't seem like the right thing to do lol. I'm done with FormField, Input, and TextArea right now so I can go ahead with another commit, but the other components I've just listed are simply commented out in the stories directory. Any suggestions?

**Comment by DominikGuzei** [comment]
@MarcusHurney i guess actually the best way would be to make one huge PR for the refactoring of the whole library because this is a complete api-breaking step that cannot "be made smoothly" 😉 So i don't really see the benefits of keeping the old components in the same repository as the new ones. Let's rename the PR to something like "Refactor library to render-props architecture"

**Comment by MarcusHurney** [comment]
@DominikGuzei Ok, it does make sense to have one big PR when you put it that way. That's what I'll do then!

**Comment by DominikGuzei** [comment]
Hey @MarcusHurney, what's the status on this PR? Can i start reviewing today/tomorrow? :)

**Comment by MarcusHurney** [comment]
Hi Dominik,

I had the logic board on my computer crash so there was a bit of a delay
there. I will be making the PR today (February 6th). I ported in the
changes from the latest PR as well.

- Marcus

**Comment by MarcusHurney** [comment]
@DominikGuzei The commits authored by Cat Tien Nguyen are mine as well. As I mentioned, my logic board crashed, so I am using my partner's computer. Besides necessary adjustments you find during review, this wraps up the refactor!

**Pull request closed without merging**
