### PR TITLE
[DDW-170] Improved Password input

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR improves the previous implementation of the `PasswordInput` component to include a configurable password strength algorithm based on basic string entropy:

grafik

Included Features:

- Configurable, entropy based password strength algorithm
- 4 different controllable (or dynamically chosen) states of the password input - default, insecure, weak, strong 
- Various UX options to control how the tooltips are shown: on hover, on focus, combined or always, debounced (only after initial user input is given etc.)
- It's possible (though not perfectly beautiful yet) to render a password repeat mode (see example in Storybook)

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@nikolaglumac the text itself is vertically centered (this is just a standard `Input` component) but since the asteriks (*) are not vertically centered characters it appears a bit pushed up … the same happens on `<Input type="password" …>`

So this could only be fixed by *not centering*  the input text, so that the asteriks appear to be centered vertically.

**Comment by DominikGuzei** [comment]
@nikolaglumac any password inputs should be vertically centered now 👍

**Comment by nikolaglumac** [comment]
@a-rukin please check this out 🙏

**Comment by a-rukin** [comment]
image
font of tooltips is light now -> should be medium

**Comment by a-rukin** [comment]
few minor improvements:
- lets add "border-radius: 1px;" for these progreses
- for the ".SimplePasswordInput_indicator" lets add "top: -2px;" + "left: 1px;" + "width: calc(100% - 2px);"
it improves look and feel for these lines ))

**Comment by DominikGuzei** [comment]
@a-rukin styling issues should be fixed now 👍

**Comment by a-rukin** [comment]
image

does it make "medium font" default one? 
It shouldn't be I think, as it will change the current tooltips

**Comment by DominikGuzei** [comment]
@a-rukin i refactored it so that only the password input tooltips are medium font now 👍

**Comment by a-rukin** [comment]
image
it should be "light"

**Comment by a-rukin** [comment]
@DominikGuzei ⬆️

**Comment by DominikGuzei** [comment]
@a-rukin great catch, fixed now 👍

**Pull request merged**
