### PR TITLE
[DDW-658] Custom select value and Stepper component

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces Custom select value renderer that can replace selected value default input rendered value. Also this PR introduces Stepper component as steps progress bar indicator.

## How to Test

- Custom Select value (`Select -> custom select value template`) - Select any select option and both label and value should appear as selected value
- Go to `Stepper` section and walk through different scenarios.

 **Note:**  Both tests are related to https://zpl.io/aBRGAeA step 1 _"choose wallet"_ step

## Screenshots

_Custom Select Value_

Custom select value

_Stepper Component_

Stepper Component

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@MarcusHurney please review this one and take care of releasing new version of React-Polymorph so that @tomothespian can continue with his work on DDW-658 🙏

**Comment by tomothespian** [comment]
> @tomothespian Great job on this! 👍
> 
> I changed the name of the selected option render prop from `valueRenderer` to `selectionRenderer`, as well as some other improvements. Feel free to take a look at those if you'd like, but the only one that will directly affect your work in Daedalus is the renaming of the prop I've mentioned above.

@MarcusHurney I saw your changes and there are few really nice improvements as well as much more better property name `selectionRenderer `. Thanks on that 🥇

**Comment by MarcusHurney** [comment]
@tomothespian I was pleasantly surprised at how well you made the new component and feature fit into the existing architecture. I know you've worked with react-polymorph before, but a lot has changed since then. Very good work! 😃

**Comment by tomothespian** [comment]
@MarcusHurney thank you soo much. 🎉

**Pull request merged**
