### PR TITLE
[DDW-602] - Improve PIN entry component UX

### PR DESCRIPTION
**Pull request by aleksandardjordjeviciohk**
This PR changes the `NumericInput` component to improve the Daedalus PIN entry component UX and logic handling for PIN input fields focus, add/remove & disallowing entry of special characters. 

## Screenshots

Screen Shot 2021-03-22 at 4 22 26 AM

Screen Shot 2021-03-22 at 4 22 36 AM

Screen Shot 2021-03-22 at 4 22 51 AM
Screen Shot 2021-03-22 at 4 23 47 AM

Screen Shot 2021-03-22 at 4 23 00 AM

Screen Shot 2021-03-22 at 4 23 22 AM

Screen Shot 2021-03-22 at 4 23 35 AM

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616408886056400)

---

## Test Scenarios

**Scenario 1 - Replace a digit to unmatch the PINs**
```gherkin
Given that I am on the fourth step of the "Register for Fund3 voting" dialog
And the PIN was repeated on both fields
And the "Continue" button is enabled
When I replace one of the digits on any pin with a different value
Then I can see the "Continue" button is disabled as the values don't match
And the "Repeat" input displays an alert
```
**Scenario 2 - Insert non-numeric characters as PIN**
```gherkin
Given that I am on the fourth step of the "Register for Fund3 voting" dialog
When I insert one of these characters: "-", ",", "."
Then they are not inserted on the fields
```
---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by DominikGuzei — CHANGES_REQUESTED** [review]
Hey @aleksandardjordjeviciohk, I would like to avoid adding application-specific code like "pin code signs" to a generic `NumericInput` component – what was your intention for this PR? I can help you if you help me understand what you are trying to do :)

**Comment by DominikGuzei** [comment]
@aleksandardjordjeviciohk like we discussed in our call, let's rename the application-specific prop `pinCodeSigns` to something more generic like `allowOnlyIntegers` + support signed integers

**Comment by aleksandardjordjeviciohk** [comment]
> @aleksandardjordjeviciohk like we discussed in our call, let's rename the application-specific prop `pinCodeSigns` to something more generic like `allowOnlyIntegers` + support signed integers

@DominikGuzei Renamed param to 'allowOnlyIntegers' and updated regex to support signed integers

**Comment by DominikGuzei** [comment]
@aleksandardjordjeviciohk the basic idea works but we have a new issue now - since bignumber.js still adds the group separators on bigger integers it causes a bug where it gets stuck on that number and you cannot delete or add anything anymore:

https://user-images.githubusercontent.com/172414/113345024-2696d880-9332-11eb-9186-c04f47fef0c8.mp4

**Comment by DominikGuzei** [comment]
@aleksandardjordjeviciohk and please add a story for all combinations:

1. `allowSigns={false}`
1. `allowOnlyIntegers` + `allowSigns`
2. `allowOnlyIntegers` + `allowSigns={false}`

**Comment by aleksandardjordjeviciohk** [comment]
> @aleksandardjordjeviciohk and please add a story for all combinations:
> 
> 1. `allowSigns={false}`
> 2. `allowOnlyIntegers` + `allowSigns`
> 3. `allowOnlyIntegers` + `allowSigns={false}`

Added @DominikGuzei

**Comment by aleksandardjordjeviciohk** [comment]
> @aleksandardjordjeviciohk the basic idea works but we have a new issue now - since bignumber.js still adds the group separators on bigger integers it causes a bug where it gets stuck on that number and you cannot delete or add anything anymore:
> 
>  CleanShot.2021-04-01.at.21.32.31.mp4

Managed to resolve this by avoiding custom or default number formatting for this particular case and just casting format from BigNumber to normal string with '.toString()' method.

**Review by DominikGuzei — CHANGES_REQUESTED** [review]
Looks much better now 🎉 only the story with `allowSigns=false | allowOnlyIntegers=true` is not correct (I can enter a sign):

https://user-images.githubusercontent.com/172414/113425797-c86e0200-93d2-11eb-8ee9-e5a22da0ed41.mp4

**Comment by aleksandardjordjeviciohk** [comment]
> Looks much better now 🎉 only the story with `allowSigns=false | allowOnlyIntegers=true` is not correct (I can enter a sign):
> 
>  CleanShot.2021-04-02.at.16.43.48.mp4

Fixed

**Review by DominikGuzei — APPROVED** [review]
Looks great now 🎉

**Comment by DominikGuzei** [comment]
@aleksandardjordjeviciohk released as `react-polymorph@0.9.8-rc.14`

**Pull request merged**
