### PR TITLE
[DDW-446] Add display name to components

### PR DESCRIPTION
**Pull request by MarcusHurney**
This PR adds a `displayName` static property to all components for semantic convenience when using react developer tools and for targeting a component by its `displayName` in tests.

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@MarcusHurney what's the story behind this WIP PR?

**Comment by MarcusHurney** [comment]
@DominikGuzei 
The latest commit reverts the changes made in the first two commits, which added a `getDisplayName` utility function and its usage in `withTheme`. This is no longer needed because `withTheme` will be removed in your upcoming PR for `DDW-371`. In terms of changes, all that remains in this PR  is the addition of `displayName` static property to each component.

**Comment by DominikGuzei** [comment]
@MarcusHurney oh no! Im not removing `withTheme` in my PR, im just improving it's typings, so that from the outside it looks like the wrapped component for Flow.js (and thus we get proper type checking) … removing `withTheme` would not be possible without destroying most of the functionality from what i saw.

**Comment by nikolaglumac** [comment]
@MarcusHurney @DominikGuzei I hope you guys will be able to sort this out 🙏

**Comment by MarcusHurney** [comment]
@DominikGuzei 

This potential miscommunication isn't a big deal either way because this PR doesn't contain any extensive work 😀I remember discussing with you the need to pull the code from `withTheme` into each individual component so the flow properties are exposed and checked one level deep instead of the current setup where `withTheme` essentially obfuscates the components flow types from being checked because it wraps the actual component. If the solution you are working on prevents the need to do this repetitive duplication of the `withTheme` code in every component then that's great. What I was originally doing in this PR is composing the component's display name to reflect the nested structure like so `withTheme(${componentName})`. The component's display name would end up looking like: `withTheme(AutoComplete)` or `withTheme(NumericInput)`. Since I thought you were pulling the `withTheme` code into each component and removing the file, I deleted this name composition since it took place inside `withTheme`.

**Comment by DominikGuzei** [comment]
@MarcusHurney perfect - my fix is not changing anything to the code structure - it's only the type signatures that are changed. So your `withTheme([displayName])` change is good 👍

**Pull request merged**
