### PR TITLE
Feature/ddw 198 extend react polymorph autocomplete to complete selection using space key

### PR DESCRIPTION
**Pull request by MarcusHurney**
Adds event handler for space key in the Options.js **_handleKeydown** method.
Improves comments for better readability in _handleKeyDown.

### CODE REVIEW

**Comment by MarcusHurney** [comment]
@nikolaglumac Maybe I was suppose to select you as a reviewer before making the PR, sorry about that.

**Comment by nikolaglumac** [comment]
@MarcusHurney we should wait with the merge of this PR until this one is merged: https://github.com/input-output-hk/react-polymorph/pull/53

**Comment by nikolaglumac** [comment]
@MarcusHurney could you also rebase this PR too like you did on this one: https://github.com/input-output-hk/react-polymorph/pull/58
Thanks!

**Comment by MarcusHurney** [comment]
@nikolaglumac 
~ convoluted commit history obliterated ~
As Napoleon once said, 'What is history, but a fable agreed upon?”

**Pull request merged**
