### PR TITLE
Fix/ddw 232 fix react polymorph input text font

### PR DESCRIPTION
**Pull request by MarcusHurney**
Changes Input's font to theme-font-regular and placeholder to theme-font-light.
Change's an Option's font to theme-font-regular.
Sets Select's input placeholder to theme-font-light via new configurable variable.

### CODE REVIEW

**Comment by MarcusHurney** [comment]
@nikolaglumac I am not seeing anywhere to add a label or request a reviewer on this PR. I am thinking that feature is only open to members of the Org so I'll add those once I accept the invite.

**Comment by nikolaglumac** [comment]
@MarcusHurney we should wait with the merge of this PR until this one is merged: https://github.com/input-output-hk/react-polymorph/pull/53

**Comment by MarcusHurney** [comment]
@nikolaglumac 
All necessary stylistic changes have been made on PR #53 that Dominik requested.

**Comment by nikolaglumac** [comment]
@MarcusHurney could you also rebase this PR too like you did on this one: https://github.com/input-output-hk/react-polymorph/pull/58
Thanks!

**Comment by MarcusHurney** [comment]
@nikolaglumac 
We would like to inform you that the rebase you requested is complete. If there is anything our customer service team can do for you in the future, please don't hesitate to contact us. Thank you for your business ! 💯

**Pull request merged**
