### PR TITLE
Feature/ddw 149 render props architecture

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR is the continuous effort of #39 

Problems to fix:

- [x] Select is not rendering the arrow within the input
- [x] #49 needs to be ported over
- [x] Improve theming API for components, so that you can pass a theme struct to any component and it passes it further down the hierarchy (for nested components). To make it easier to customize nested comps.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@MarcusHurney please review this PR, which builds apon your great refactor 😉 

## Improved Theming Logic:

Theming and overriding component styles is more consistent now. You always have to pass an object that adheres to the `themeAPI`, which works on three different layers:

  1. **ThemeProvider**: You pass a complete theme (like before), any component picks up the base theme automatically.
  2. **Component theme**: You can provide a custom theme by passing `theme={customTheme}` to any component and it automatically passes down the `customTheme` down to nested components too. This allows theming changes per component, which do not affect other parts of the app. The custom theme completely replaces the theme from the `ThemeProvider`
  3. **Theme Overrides**: follows the same structure as a normal theme but is applied "on top", so you don't have to provide a full theme but can only provide smaller overrides (this is more economic in turns of produced CSS than `theme={customTheme}`) … e.g: `themeOverrides={{ [IDENTIFIERS.BUTTON]: myButtonOverrides }}`

I added examples for these features to the storybook!

**Comment by MarcusHurney** [comment]
@DominikGuzei 

I tested out the updates and found a few bugs. I went ahead and fixed those and made a PR to merge those into this one.

**Comment by nikolaglumac** [comment]
@MarcusHurney @DominikGuzei I think this PR is ready to be merged. Can you please take care of the merge conflicts and merge it? Thanks!

**Comment by nikolaglumac** [comment]
@MarcusHurney @DominikGuzei I have removed the `WIP` tag as I believe this one is done.

**Comment by MarcusHurney** [comment]
@nikolaglumac 
Ready for merge!

**Pull request merged**
