### PR TITLE
[DDW-497] Improve autocomplete required selections ux

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR improves the Autocomplete `requiredSelections` prop UX with an optional `requiredSelectionsInfo` prop - a function that gets the required and actual selections as inputs and returns any string which is displayed above the autocomplete:

**Note:** The "x of x words selected" string is not generated by react-polymorph but by a callback function which can return any string for the given params like this: `(required, actual) => `${actual} words entered`

## Explanation:

The feature consists of the combination of multiple props:

```js
maxSelections={7}
requiredSelections={[3, 5, 7]}
requiredSelectionsInfo={(required, actual) => `${actual} words entered`}
```

- `requiredSelections` contains any number of possible "target counts" of selections
- `requiredSelectionsInfo` is a callback function `(required, actual) => `${actual} words entered` that returns any string which is rendered on the top right above the Autocomplete (which can be used to show the user useful feedback about the words entered etc.)
- `maxSelections` restricts the maximum number of selections (should always be higher than the biggest `requiredSelection`)

### `requiredSelections={[3]}` (only a single count -> "x of x words …")
CleanShot 2020-12-14 at 17 54 29

### `requiredSelections={[3, 5, 7]}` (multiple counts -> "x words entered …"
CleanShot 2020-12-14 at 17 58 44

## Todos:

- [x] Handle the case where we expected one of the specified phrase lengths: 18, 24 or 27

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei how about the case where we expected one of the specified phrase lengths: 18, 24 or 27?

**Comment by DominikGuzei** [comment]
@nikolaglumac sorry, forgot to flag this as WIP - it's not finished yet but actually good that you reviewed because I'm not sure about the case you described - will check the designs / talk to Sasha

**Comment by DominikGuzei** [comment]
@nikolaglumac multiple target counts are now implemented and i improved the PR description with better explanation + examples 👍

**Comment by DominikGuzei** [comment]
But let's leave this in WIP state until the integration in Daedalus is finished 😉

**Comment by gnpf** [comment]
These scenarios on Storybook look good 👍 
I'll approve once it can be tested on Daedalus.

**Pull request merged**
