### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR prepares the 1.0 release and introduces a new release management process.

## 🤓 New Release Management

- Starting with `1.0.0` all future releases will follow semver semantics:
  - `patch` (eg: 1.0.x) for **API compatible bug fixes**
  - `minor` (eg.: 1.x.0) for **API compatible new features**
  - `major` (eg: 2.0.0) for **API breaking changes**
  
- For early integration of upcoming release changes we use the following conventions:
  
  - `[current version]-next.x` to tag changes for upcoming releases (as we cannot know the necessary 
    semver for the final release including all the changes). `x` in this case is simply a number that 
    is increased and can be thought of like "slots" for temporary releases
    
  - All temporary releases should be published with the `next` npm dist tag via: `npm publish --tag next` 
    so that they are not automatically tagged with the default `latest` npm tag.
    
- The `master` branch only includes commits of final releases
  
- `release/x.x.x` branches are created as soon as we cut a release and know the correct semver - they 
  are always targeting the `master` branch + should be well documented. They can include many release
  candidates which should be tagged like `[next releaes]-rc.X` where you increment X per release candidate
  until we are confident that the release is ready to be published under its normal version.

### Breaking Changes :boom:

- `Input` now shows errors on hover and focus by default which can be configured via two new props ([PR 173](https://github.com/input-output-hk/react-polymorph/pull/173))

```ts
  isShowingErrorOnFocus: boolean,
  isShowingErrorOnHover: boolean,
```

### ✨ Features 

- Implemented the search functionality to the Options component ([PR 165](https://github.com/input-output-hk/daedalus/pull/165))
- Improved PIN entry component UX ([PR 166](https://github.com/input-output-hk/react-polymorph/pull/166))
- Enabled pasting of multiple words into Autocomplete ([PR 163](https://github.com/input-output-hk/react-polymorph/pull/163))

### 🐞 Fixes 

- Fixed Select search issues ([PR 179](https://github.com/input-output-hk/react-polymorph/pull/179))
- Fixed Select Search styles and minor code issues ([PR 175](https://github.com/input-output-hk/react-polymorph/pull/175))
- Fixed a wrong variable name for the select search highlight color ([PR 170](https://github.com/input-output-hk/react-polymorph/pull/170))
- Fixed an issue related to Numeric Input when entering numbers after having selected the decimal separator ([PR 167](https://github.com/input-output-hk/react-polymorph/pull/167))
- Fixed issues related to controlled/uncontrolled Tippy state ([PR 160](https://github.com/input-output-hk/react-polymorph/pull/160))
- Fixed `NumericInput` to support DEBUG mode ([PR 159](https://github.com/input-output-hk/react-polymorph/pull/159))

## ⌛ Potential Changes Waiting for Review

- [[DDW-603] Enable pasting of wallet recovery phrase ](https://github.com/input-output-hk/react-polymorph/pull/168)

### CODE REVIEW

**Comment by DominikGuzei** [comment]
First release candidate is available as `1.0.0-rc.1`

**Review by nikolaglumac — APPROVED** [review]
Perfect 💯

**Comment by nikolaglumac** [comment]
@DominikGuzei please proceed with the release. I have merged this so that I can close the JIRA card.

**Comment by DominikGuzei** [comment]
@nikolaglumac i should have added a note here … @daniloprates hasn't merged https://github.com/input-output-hk/react-polymorph/pull/179 into the release yet … so this is not included now 😢 but it's ok, we can make another release with Danilos changes and @aleksandardjordjeviciohk PR https://github.com/input-output-hk/react-polymorph/pull/168

**Comment by nikolaglumac** [comment]
Sorry to cause issues. Let’s be more careful next time...

**Comment by daniloprates** [comment]
> @nikolaglumac i should have added a note here … @daniloprates hasn't merged #179 into the release yet … so this is not included now 😢 but it's ok, I will add this locally and make another release candidate

@DominikGuzei I [did merge](https://github.com/input-output-hk/react-polymorph/pull/178/commits/2cfeb62681e0b47f7ad3246463ff1440fc0a6ef3) 🤔

**Comment by DominikGuzei** [comment]
@daniloprates my fault, somehow I didn't see your commits - it's all released into 1.0.0 👍

**Pull request merged**
